#pragma once
#define EE_HANDS

#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_MOVE_DELTA 7
#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_DELAY 25
#define MOUSEKEY_WHEEL_INTERVAL 90
#define MOUSEKEY_WHEEL_MAX_SPEED 20
#define MOUSEKEY_WHEEL_TIME_TO_MAX 15

// TAP MOD SETTINGS
#define TAPPING_TERM 160
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define TAPPING_TERM_PER_KEY

// COMBOS
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 25
#define COMBO_COUNT 76
