#pragma once
#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_TIME_TO_MAX 12
#define MOUSEKEY_DELAY 45
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_MAX_SPEED 20
#define MOUSEKEY_WHEEL_TIME_TO_MAX 20

// TAP MOD SETTINGS
#define TAPPING_TERM 165
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define TAPPING_TERM_PER_KEY

// COMBOS
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_COUNT 10

