#pragma once
#define MOUSEKEY_INTERVAL 15
#define MOUSEKEY_TIME_TO_MAX 15
#define MOUSEKEY_DELAY 75
#define MOUSEKEY_WHEEL_DELAY 20
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_TIME_TO_MAX 20

// TAP MOD SETTINGS
#define TAPPING_TERM 165
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define TAPPING_TERM_PER_KEY

// COMBOS
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_COUNT 2

// CAPS WORD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
